name: ci

on:
  push:
  pull_request:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run lint
  format:
    name: format
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run check-format
  type-check:
    name: type-check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run type-check
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
